### ISSUE TITLE
Pattern Entities no longer in BETA - Replace screenshots

### ISSUE THREAD

**Issue by amblock** [IBM-Bluemix-Docs/conversation#209]
This is a really small issue but I thought it would be nice to replace the screenshots for pattern entities.

https://github.com/IBM-Bluemix-Docs/conversation/blob/master/entities.md

![image](https://user-images.githubusercontent.com/13277874/36733092-858677de-1b9d-11e8-9036-9da66b9c44d8.png)

![image](https://user-images.githubusercontent.com/13277874/36733100-8a394608-1b9d-11e8-9b5d-cd5e1854b299.png)

**Comment by kmacdonald06** [comment]
Updated in production
