### ISSUE TITLE
Location of the source code?

### ISSUE THREAD

**Issue by service-management-unite** [IBM-Bluemix-Docs/conversation#340]
Hello,

I'm quite interested in the '[banking demo]( https://watson-conversation-duo-dev.ng.bluemix.net/)'
Is this open source? And where can I download the source code?

**Comment by michelle-miller** [comment]
I checked with the developer. They are planning to release the source code, but have some updated they plan to make first. When they do make it available, it will be published to the [Watson Developer Cloud GitHub repository](https://github.com/watson-developer-cloud). So, keep an eye out there. Likely January/February 2019 time frame.
