### ISSUE TITLE
how to send Dynamic Option response

### ISSUE THREAD

**Issue by AliAhmedNada** [IBM-Bluemix-Docs/conversation#365]
hello 

I am trying to inject Dymanic Options list from a return from Dialogue actions , it seems like it is impossible to add a variable that can show options structure , is this feature available , it seems simple thing but it have a huge impact on UI / UX experience 

and can anyone show me an example

thanks

**Comment by michelle-miller** [comment]
Looks like my colleague Mitchell Mason answered this question on the Slack thread here: https://wdc-community.slack.com/messages/C0A239C04/convo/C0A239C04-1542114201.123600/.

**Comment by AliAhmedNada** [comment]
hello @michelle-miller 

i have made a workaround that i should loop inside watson assistant , instead of sending it from a service , 
now another Problem , it is Working on tryout watson assistant , and not working on facebook integration 

![image](https://user-images.githubusercontent.com/17008257/48485315-2b21cb80-e821-11e8-828a-4e1e6fb42603.png)

**Comment by michelle-miller** [comment]
the response types can behave differently in different integrations. see https://console.bluemix.net/docs/services/assistant/deploy-facebook.html#facebook-dialog for details about how the response types work in Facebook.

**Comment by AliAhmedNada** [comment]
@michelle-miller 
in the Documentation [https://github.com/IBM-Bluemix-Docs/conversation/blob/master/dialog-responses-json.md](url)
Native JSON format part 
it was stated that specific channel responses could be delivered , how can i do that , and is there a sample to the suggested input 

Regards

**Comment by rrberry** [comment]
To send a channel-specific response instead of a generic response, you would specify an `output.slack` or `output.facebook` object instead of `output.generic`. For example:

```
{
  "output": {
    "facebook":[
      {
        ...
      }
    ]
  }
}
```

Inside the `facebook` or `slack` object, you would send whatever JSON data that service expects. You'll need to refer to the Facebook or Slack documentation for information about their expected format (follow the links in the documentation).

Note that there is no reason to use the native JSON format unless you need to specify some kind of response that the generic format does not support.

**Comment by AliAhmedNada** [comment]
Thanks @rrberry 

i have tried this method but it this but no use kindly check below :

```
{
  "output": {
    "text": {
      "values": [
        "bye from watson "
      ],
      "selection_policy": "sequential"
    },
    "facebook": {
  "message":{
    "attachment":{
      "type":"template",
      "payload":{
        "template_type":"generic",
        "elements":[
           {
            "title":"Welcome!",
            "image_url":"https://petersfancybrownhats.com/company_image.png",
            "subtitle":"We have the right hat for everyone.",
            "default_action": {
              "type": "web_url",
              "url": "https://petersfancybrownhats.com/view?item=103",
              "webview_height_ratio": "tall",
            },
            "buttons":[
              {
                "type":"web_url",
                "url":"https://petersfancybrownhats.com",
                "title":"View Website"
              },{
                "type":"postback",
                "title":"Start Chatting",
                "payload":"DEVELOPER_DEFINED_PAYLOAD"
              }              
            ]      
          }
        ]
      }
    }
  }
    }
  }
}
```

**Comment by rrberry** [comment]
@dgterry can you help?

**Comment by dgterry** [comment]
What actually happens with that payload? Does Watson respond with "bye from watson" ? I'm wondering if having output.text is making the code not look for output.facebook.

**Comment by AliAhmedNada** [comment]
hello @dgterry

yes  bye from watson appear on facebook , but this is not the behavior that i want , it should be channel specific , am i right ?!

Regards
Ali Ahmed Nada

**Comment by dgterry** [comment]
I believe the code looks for output.text first so it probably doesn't see output.facebook.  Can you try to remove the output.text? Or are you trying to have that appear for non-facebook channels? Can you try putting output.facebook above output.text and see if that helps?

**Comment by AliAhmedNada** [comment]
okay (y) , will test now

**Comment by AliAhmedNada** [comment]
```
{
  "output": {
    "facebook": {
      "message": {
        "attachment": {
          "type": "template",
          "payload": {
            "elements": [
              {
                "title": "Welcome!",
                "subtitle": "We have the right hat for everyone.",
                "image_url": "https://petersfancybrownhats.com/company_image.png",
                "default_action": {
                  "url": "https://petersfancybrownhats.com/view?item=103",
                  "type": "web_url",
                  "webview_height_ratio": "tall"
                }
              }
            ],
            "template_type": "generic"
          }
        }
      }
    },
    "text": {
      "values": [],
      "selection_policy": "sequential"
    }
  }
}
```

nothing appear on facebook 
and error on tryout as follows : Method [jsonPath] call on type [thanks] is not supported. SpEL access error: Method [jsonPath] call on type [thanks] is not supported. (and there is 1 more error in the log)

**Comment by dgterry** [comment]
Thanks for reporting this.  It turns out there is a bug in this area and the exchange between the conversation skill and the integrations needs to be updated.

**Comment by AliAhmedNada** [comment]
Thanks @dgterry 
is there something or ticket i can follow up to know when it is fixed ?!
